-- =====================================================================
-- MASTER SCHEMA — Backend Integration Prototype
-- Generated from live Supabase database state.
--
-- HOW TO USE FOR A NEW CLIENT:
--   1. Create a new Supabase project.
--   2. Open SQL Editor.
--   3. Paste this ENTIRE file and click "Run".
--   4. Update SUPABASE_URL + SUPABASE_ANON_KEY in the frontend config.
--   5. Create the client's first auth user in Authentication > Users,
--      then INSERT a matching row into public.users with role_id pointing
--      to the 'owner' role.
--
-- This file is idempotent-ish: it uses IF NOT EXISTS / OR REPLACE where
-- possible. Running it on a fresh project is the supported path.
-- =====================================================================


-- =====================================================================
-- 1. EXTENSIONS
-- =====================================================================
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";


-- =====================================================================
-- 2. PRIVATE SCHEMA (RLS helper functions live here)
-- =====================================================================
CREATE SCHEMA IF NOT EXISTS private;


-- =====================================================================
-- 3. TABLES (created in FK dependency order)
-- =====================================================================

-- roles: master list of app roles (owner/staff)
CREATE TABLE IF NOT EXISTS public.roles (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code       text NOT NULL UNIQUE CHECK (code IN ('owner','staff')),
  label      text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);
COMMENT ON TABLE public.roles IS 'Owner/staff role master for the stock tracker.';

-- users: app user profile linked 1:1 with auth.users
CREATE TABLE IF NOT EXISTS public.users (
  id         uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role_id    bigint NOT NULL REFERENCES public.roles(id),
  full_name  text,
  phone      text,
  is_active  boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);
COMMENT ON TABLE public.users IS 'App user profile linked 1:1 with auth.users.';
CREATE INDEX IF NOT EXISTS users_role_id_idx ON public.users (role_id);

-- user_roles: legacy/alt table (kept for compatibility with user_access_view consumers)
CREATE TABLE IF NOT EXISTS public.user_roles (
  id    uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email text NOT NULL,
  role  text NOT NULL CHECK (role IN ('owner','manager'))
);

-- vendors: approved supplier master
CREATE TABLE IF NOT EXISTS public.vendors (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name              text NOT NULL UNIQUE,
  contact_name      text,
  phone             text,
  category_supplied text,
  notes             text,
  is_active         boolean NOT NULL DEFAULT true,
  created_by        uuid REFERENCES auth.users(id) DEFAULT auth.uid(),
  created_at        timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at        timestamptz NOT NULL DEFAULT timezone('utc', now())
);
COMMENT ON TABLE public.vendors IS 'Approved supplier master.';
CREATE INDEX IF NOT EXISTS vendors_active_name_idx ON public.vendors (is_active, name);

-- stock_items: single-outlet stock item master
CREATE TABLE IF NOT EXISTS public.stock_items (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name                text NOT NULL UNIQUE,
  category            text NOT NULL,
  default_unit        text NOT NULL,
  low_stock_threshold numeric NOT NULL DEFAULT 0 CHECK (low_stock_threshold >= 0),
  is_active           boolean NOT NULL DEFAULT true,
  notes               text,
  created_by          uuid REFERENCES auth.users(id) DEFAULT auth.uid(),
  created_at          timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at          timestamptz NOT NULL DEFAULT timezone('utc', now())
);
COMMENT ON TABLE public.stock_items IS 'Single-outlet stock item master.';
CREATE INDEX IF NOT EXISTS stock_items_active_category_idx ON public.stock_items (is_active, category);

-- purchase_bills: supplier bill header
CREATE TABLE IF NOT EXISTS public.purchase_bills (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vendor_id      uuid REFERENCES public.vendors(id),
  bill_date      date NOT NULL DEFAULT CURRENT_DATE,
  bill_number    text,
  source         text NOT NULL DEFAULT 'manual'
                  CHECK (source IN ('manual','whatsapp_paste','upload')),
  original_text  text,
  file_url       text,
  subtotal       numeric NOT NULL DEFAULT 0,
  extra_charges  numeric NOT NULL DEFAULT 0,
  total          numeric NOT NULL DEFAULT 0,
  status         text NOT NULL DEFAULT 'draft'
                  CHECK (status IN ('draft','pending_review','approved','rejected')),
  created_by     uuid REFERENCES auth.users(id) DEFAULT auth.uid(),
  approved_by    uuid REFERENCES auth.users(id),
  approved_at    timestamptz,
  created_at     timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at     timestamptz NOT NULL DEFAULT timezone('utc', now())
);
COMMENT ON TABLE public.purchase_bills IS 'Supplier bill header before and after owner approval.';
CREATE INDEX IF NOT EXISTS purchase_bills_status_date_idx ON public.purchase_bills (status, bill_date DESC);
CREATE INDEX IF NOT EXISTS purchase_bills_vendor_date_idx ON public.purchase_bills (vendor_id, bill_date DESC);
CREATE UNIQUE INDEX IF NOT EXISTS purchase_bills_vendor_bill_number_unique_idx
  ON public.purchase_bills (vendor_id, bill_number) WHERE (bill_number IS NOT NULL);

-- purchase_bill_items: line items
CREATE TABLE IF NOT EXISTS public.purchase_bill_items (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  purchase_bill_id uuid NOT NULL REFERENCES public.purchase_bills(id) ON DELETE CASCADE,
  stock_item_id    uuid REFERENCES public.stock_items(id),
  raw_item_name    text NOT NULL,
  quantity         numeric NOT NULL CHECK (quantity > 0),
  unit             text NOT NULL,
  unit_price       numeric NOT NULL,
  line_total       numeric NOT NULL,
  confidence_score numeric CHECK (confidence_score IS NULL
                                  OR (confidence_score >= 0 AND confidence_score <= 100)),
  match_status     text NOT NULL DEFAULT 'manual_match'
                    CHECK (match_status IN ('matched','manual_match','unknown','needs_review')),
  created_at       timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at       timestamptz NOT NULL DEFAULT timezone('utc', now())
);
COMMENT ON TABLE public.purchase_bill_items IS 'Supplier bill line items mapped to stock items when possible.';
CREATE INDEX IF NOT EXISTS purchase_bill_items_bill_id_idx ON public.purchase_bill_items (purchase_bill_id);
CREATE INDEX IF NOT EXISTS purchase_bill_items_stock_item_id_idx ON public.purchase_bill_items (stock_item_id);

-- stock_movements: traceable stock ledger
CREATE TABLE IF NOT EXISTS public.stock_movements (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  stock_item_id       uuid NOT NULL REFERENCES public.stock_items(id) ON DELETE CASCADE,
  movement_type       text NOT NULL
                      CHECK (movement_type IN ('opening_stock','purchase_added','usage',
                                               'wastage','return_to_vendor','correction')),
  quantity            numeric NOT NULL CHECK (quantity > 0),
  unit                text NOT NULL,
  source_bill_item_id uuid REFERENCES public.purchase_bill_items(id) ON DELETE SET NULL,
  notes               text,
  created_by          uuid REFERENCES auth.users(id) DEFAULT auth.uid(),
  created_at          timestamptz NOT NULL DEFAULT timezone('utc', now())
);
COMMENT ON TABLE public.stock_movements IS 'Traceable stock ledger entries. Purchase stock increases must reference a bill line.';
CREATE INDEX IF NOT EXISTS stock_movements_item_created_idx ON public.stock_movements (stock_item_id, created_at DESC);
CREATE INDEX IF NOT EXISTS stock_movements_source_bill_item_id_idx ON public.stock_movements (source_bill_item_id);

-- bill_alerts: suspicious-bill detection results
CREATE TABLE IF NOT EXISTS public.bill_alerts (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  purchase_bill_id uuid NOT NULL REFERENCES public.purchase_bills(id) ON DELETE CASCADE,
  alert_type       text NOT NULL
                   CHECK (alert_type IN ('price_jump','duplicate_bill_number','total_mismatch',
                                         'high_quantity','unknown_vendor','unknown_item','unit_change')),
  severity         text NOT NULL DEFAULT 'warning' CHECK (severity IN ('warning','critical')),
  message          text NOT NULL,
  status           text NOT NULL DEFAULT 'active' CHECK (status IN ('active','resolved','dismissed')),
  resolved_by      uuid REFERENCES auth.users(id),
  resolved_at      timestamptz,
  created_at       timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at       timestamptz NOT NULL DEFAULT timezone('utc', now())
);

-- system_config: arbitrary key/value config used by triggers
CREATE TABLE IF NOT EXISTS public.system_config (
  key   text PRIMARY KEY,
  value text NOT NULL
);


-- =====================================================================
-- 4. PRIVATE HELPER FUNCTIONS (used by RLS policies)
-- =====================================================================

CREATE OR REPLACE FUNCTION private.current_user_role()
RETURNS text
LANGUAGE sql SECURITY DEFINER SET search_path = 'public','private'
AS $$
  select r.code
  from public.users u
  join public.roles r on r.id = u.role_id
  where u.id = (select auth.uid())
    and u.is_active
  limit 1
$$;

CREATE OR REPLACE FUNCTION private.is_owner()
RETURNS boolean
LANGUAGE sql SECURITY DEFINER SET search_path = 'public','private'
AS $$
  select coalesce(private.current_user_role() = 'owner', false)
$$;

CREATE OR REPLACE FUNCTION private.is_active_app_user()
RETURNS boolean
LANGUAGE sql SECURITY DEFINER SET search_path = 'public','private'
AS $$
  select private.current_user_role() in ('owner','staff')
$$;

CREATE OR REPLACE FUNCTION private.can_access_bill(target_bill_id uuid)
RETURNS boolean
LANGUAGE sql SECURITY DEFINER SET search_path = 'public','private'
AS $$
  select exists (
    select 1 from public.purchase_bills b
    where b.id = target_bill_id
      and (private.is_owner() or b.created_by = (select auth.uid()))
  )
$$;

CREATE OR REPLACE FUNCTION private.can_manage_bill_lines(target_bill_id uuid)
RETURNS boolean
LANGUAGE sql SECURITY DEFINER SET search_path = 'public','private'
AS $$
  select exists (
    select 1 from public.purchase_bills b
    where b.id = target_bill_id
      and (
        private.is_owner()
        or (b.created_by = (select auth.uid())
            and b.status in ('draft','pending_review'))
      )
  )
$$;


-- =====================================================================
-- 5. PUBLIC FUNCTIONS (used by triggers)
-- =====================================================================

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

CREATE OR REPLACE FUNCTION public.evaluate_bill_alerts(bill_id uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER AS $$
declare
  b_rec record;
  item_rec record;
  prev_price numeric(12,2);
  avg_qty numeric(12,3);
  total_items_price numeric(12,2) := 0;
  duplicate_count integer;
  prev_qty_count integer;
begin
  select pb.*, v.name as vendor_name
  into b_rec
  from public.purchase_bills pb
  left join public.vendors v on pb.vendor_id = v.id
  where pb.id = bill_id;

  if not found then return; end if;

  delete from public.bill_alerts
  where purchase_bill_id = bill_id and status = 'active';

  if b_rec.bill_number is not null and b_rec.vendor_id is not null then
    select count(*) into duplicate_count
    from public.purchase_bills
    where id <> bill_id and bill_number = b_rec.bill_number
      and vendor_id = b_rec.vendor_id;

    if duplicate_count > 0 then
      insert into public.bill_alerts (purchase_bill_id, alert_type, severity, message)
      values (bill_id, 'duplicate_bill_number', 'critical',
        'Bill number ' || b_rec.bill_number || ' from ' || b_rec.vendor_name
        || ' was already entered. This bill may be a duplicate.');
    end if;
  end if;

  if b_rec.vendor_id is null then
    insert into public.bill_alerts (purchase_bill_id, alert_type, severity, message)
    values (bill_id, 'unknown_vendor', 'warning',
      'Vendor is not on your approved list. Add them in Stock Setup, or fix the spelling on the bill.');
  end if;

  for item_rec in
    select pbi.*, si.name as stock_item_name, si.default_unit as stock_default_unit
    from public.purchase_bill_items pbi
    left join public.stock_items si on pbi.stock_item_id = si.id
    where pbi.purchase_bill_id = bill_id
  loop
    total_items_price := total_items_price + item_rec.line_total;

    if item_rec.stock_item_id is null then
      insert into public.bill_alerts (purchase_bill_id, alert_type, severity, message)
      values (bill_id, 'unknown_item', 'warning',
        '"' || item_rec.raw_item_name || '" is not in your stock list. Add it in Stock Setup so future bills match it automatically.');
    else
      if item_rec.unit <> item_rec.stock_default_unit then
        insert into public.bill_alerts (purchase_bill_id, alert_type, severity, message)
        values (bill_id, 'unit_change', 'warning',
          item_rec.stock_item_name || ' is billed in "' || item_rec.unit
          || '" but you usually track it in "' || item_rec.stock_default_unit
          || '". Double-check the quantity.');
      end if;

      select pbi.unit_price into prev_price
      from public.purchase_bill_items pbi
      join public.purchase_bills pb on pbi.purchase_bill_id = pb.id
      where pb.status = 'approved' and pbi.stock_item_id = item_rec.stock_item_id
        and pb.id <> bill_id
      order by pb.bill_date desc, pb.created_at desc
      limit 1;

      if prev_price is not null and prev_price > 0 then
        if item_rec.unit_price > (prev_price * 1.20) then
          declare pct_inc numeric;
          begin
            pct_inc := ((item_rec.unit_price - prev_price) / prev_price) * 100;
            insert into public.bill_alerts (purchase_bill_id, alert_type, severity, message)
            values (bill_id, 'price_jump', 'critical',
              item_rec.stock_item_name || ' price jumped ' || round(pct_inc, 0)
              || '%: now ₹' || item_rec.unit_price || ', last time ₹' || prev_price
              || '. Confirm the new rate before approving.');
          end;
        end if;
      end if;

      select avg(pbi.quantity), count(*) into avg_qty, prev_qty_count
      from (
        select pbi.quantity
        from public.purchase_bill_items pbi
        join public.purchase_bills pb on pbi.purchase_bill_id = pb.id
        where pb.status = 'approved' and pbi.stock_item_id = item_rec.stock_item_id
          and pb.id <> bill_id
        order by pb.bill_date desc, pb.created_at desc
        limit 5
      ) pbi;

      if prev_qty_count >= 2 and avg_qty > 0 then
        if item_rec.quantity > (avg_qty * 3.0) then
          insert into public.bill_alerts (purchase_bill_id, alert_type, severity, message)
          values (bill_id, 'high_quantity', 'warning',
            'Large order of ' || item_rec.stock_item_name || ': ' || item_rec.quantity
            || ' vs typical ~' || round(avg_qty, 1) || '. Confirm this much was actually ordered.');
        end if;
      end if;
    end if;
  end loop;

  if abs(b_rec.total - (total_items_price + b_rec.extra_charges)) > 0.05 then
    insert into public.bill_alerts (purchase_bill_id, alert_type, severity, message)
    values (bill_id, 'total_mismatch', 'critical',
      'Bill total ₹' || b_rec.total || ' does not match line items + charges (₹'
      || (total_items_price + b_rec.extra_charges) || '). Check the math before approving.');
  end if;
end;
$$;

CREATE OR REPLACE FUNCTION public.process_bill_approval()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER AS $$
declare item_row record;
begin
  if new.status = 'approved' and (old.status is null or old.status <> 'approved') then
    new.approved_by := coalesce(new.approved_by, auth.uid());
    new.approved_at := coalesce(new.approved_at, now());

    for item_row in
      select id, stock_item_id, quantity, unit
      from public.purchase_bill_items
      where purchase_bill_id = new.id
    loop
      insert into public.stock_movements (
        stock_item_id, movement_type, quantity, unit,
        source_bill_item_id, notes, created_by
      ) values (
        item_row.stock_item_id, 'purchase_added', item_row.quantity, item_row.unit,
        item_row.id,
        'Auto-added via bill approval: ' || coalesce(new.bill_number, new.id::text),
        coalesce(new.approved_by, auth.uid())
      );
    end loop;
  end if;
  return new;
end;
$$;

CREATE OR REPLACE FUNCTION public.tr_evaluate_bill_alerts_bill()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER AS $$
begin
  if new.status in ('draft','pending_review') then
    perform public.evaluate_bill_alerts(new.id);
  end if;
  return new;
end;
$$;

CREATE OR REPLACE FUNCTION public.tr_evaluate_bill_alerts_item()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER AS $$
declare bill_id uuid; bill_status text;
begin
  if tg_op = 'DELETE' then bill_id := old.purchase_bill_id;
  else bill_id := new.purchase_bill_id; end if;

  select status into bill_status from public.purchase_bills where id = bill_id;
  if bill_status in ('draft','pending_review') then
    perform public.evaluate_bill_alerts(bill_id);
  end if;

  if tg_op = 'DELETE' then return old; else return new; end if;
end;
$$;

CREATE OR REPLACE FUNCTION public.tr_resolve_bill_alerts_on_status_change()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER AS $$
begin
  if new.status in ('approved','rejected') and old.status not in ('approved','rejected') then
    update public.bill_alerts
    set status = 'resolved',
        resolved_by = coalesce(auth.uid(), new.approved_by),
        resolved_at = now()
    where purchase_bill_id = new.id and status = 'active';
  end if;
  return new;
end;
$$;


-- =====================================================================
-- 6. TRIGGERS
-- =====================================================================

DROP TRIGGER IF EXISTS users_set_updated_at ON public.users;
CREATE TRIGGER users_set_updated_at BEFORE UPDATE ON public.users
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS vendors_set_updated_at ON public.vendors;
CREATE TRIGGER vendors_set_updated_at BEFORE UPDATE ON public.vendors
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS stock_items_set_updated_at ON public.stock_items;
CREATE TRIGGER stock_items_set_updated_at BEFORE UPDATE ON public.stock_items
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS purchase_bills_set_updated_at ON public.purchase_bills;
CREATE TRIGGER purchase_bills_set_updated_at BEFORE UPDATE ON public.purchase_bills
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS purchase_bill_items_set_updated_at ON public.purchase_bill_items;
CREATE TRIGGER purchase_bill_items_set_updated_at BEFORE UPDATE ON public.purchase_bill_items
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS tr_process_bill_approval ON public.purchase_bills;
CREATE TRIGGER tr_process_bill_approval BEFORE UPDATE ON public.purchase_bills
  FOR EACH ROW EXECUTE FUNCTION public.process_bill_approval();

DROP TRIGGER IF EXISTS tr_evaluate_bill_alerts_bill ON public.purchase_bills;
CREATE TRIGGER tr_evaluate_bill_alerts_bill AFTER INSERT OR UPDATE ON public.purchase_bills
  FOR EACH ROW EXECUTE FUNCTION public.tr_evaluate_bill_alerts_bill();

DROP TRIGGER IF EXISTS tr_resolve_bill_alerts_on_status_change ON public.purchase_bills;
CREATE TRIGGER tr_resolve_bill_alerts_on_status_change AFTER UPDATE ON public.purchase_bills
  FOR EACH ROW EXECUTE FUNCTION public.tr_resolve_bill_alerts_on_status_change();

DROP TRIGGER IF EXISTS tr_evaluate_bill_alerts_item ON public.purchase_bill_items;
CREATE TRIGGER tr_evaluate_bill_alerts_item AFTER INSERT OR UPDATE OR DELETE ON public.purchase_bill_items
  FOR EACH ROW EXECUTE FUNCTION public.tr_evaluate_bill_alerts_item();


-- =====================================================================
-- 7. VIEWS
-- =====================================================================

CREATE OR REPLACE VIEW public.user_access_view AS
  SELECT u.id, u.full_name, u.phone, u.is_active,
         r.code AS role_code, r.label AS role_label
  FROM public.users u
  JOIN public.roles r ON r.id = u.role_id;

CREATE OR REPLACE VIEW public.stock_item_balances AS
  SELECT si.id AS stock_item_id, si.name, si.category, si.default_unit,
         si.low_stock_threshold, si.is_active,
         COALESCE(sum(
           CASE sm.movement_type
             WHEN 'opening_stock'    THEN sm.quantity
             WHEN 'purchase_added'   THEN sm.quantity
             WHEN 'usage'            THEN -sm.quantity
             WHEN 'wastage'          THEN -sm.quantity
             WHEN 'return_to_vendor' THEN -sm.quantity
             WHEN 'correction'       THEN sm.quantity
             ELSE 0::numeric
           END), 0::numeric) AS current_quantity,
         (COALESCE(sum(
           CASE sm.movement_type
             WHEN 'opening_stock'    THEN sm.quantity
             WHEN 'purchase_added'   THEN sm.quantity
             WHEN 'usage'            THEN -sm.quantity
             WHEN 'wastage'          THEN -sm.quantity
             WHEN 'return_to_vendor' THEN -sm.quantity
             WHEN 'correction'       THEN sm.quantity
             ELSE 0::numeric
           END), 0::numeric) <= si.low_stock_threshold) AS is_low_stock
  FROM public.stock_items si
  LEFT JOIN public.stock_movements sm ON sm.stock_item_id = si.id
  GROUP BY si.id;


-- =====================================================================
-- 8. ENABLE ROW LEVEL SECURITY
-- =====================================================================
ALTER TABLE public.roles               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.vendors             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_items         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_bills      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_bill_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_movements     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bill_alerts         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_config       ENABLE ROW LEVEL SECURITY;


-- =====================================================================
-- 9. RLS POLICIES
-- =====================================================================

-- roles
DROP POLICY IF EXISTS "authenticated users can read roles" ON public.roles;
CREATE POLICY "authenticated users can read roles" ON public.roles
  FOR SELECT TO authenticated
  USING ((SELECT auth.uid()) IS NOT NULL);

-- users
DROP POLICY IF EXISTS "users can read own profile" ON public.users;
CREATE POLICY "users can read own profile" ON public.users
  FOR SELECT TO authenticated USING (id = (SELECT auth.uid()));

DROP POLICY IF EXISTS "owners can read all users" ON public.users;
CREATE POLICY "owners can read all users" ON public.users
  FOR SELECT TO authenticated USING (private.is_owner());

DROP POLICY IF EXISTS "owners can manage users" ON public.users;
CREATE POLICY "owners can manage users" ON public.users
  FOR ALL TO authenticated USING (private.is_owner()) WITH CHECK (private.is_owner());

-- user_roles
DROP POLICY IF EXISTS "Allow anyone to read roles" ON public.user_roles;
DROP POLICY IF EXISTS "users can read own role row" ON public.user_roles;
CREATE POLICY "users can read own role row" ON public.user_roles
  FOR SELECT TO authenticated
  USING (id = (SELECT auth.uid()) OR private.is_owner());

-- vendors
DROP POLICY IF EXISTS "active users can read vendors" ON public.vendors;
CREATE POLICY "active users can read vendors" ON public.vendors
  FOR SELECT TO authenticated USING (private.is_active_app_user());

DROP POLICY IF EXISTS "owners can manage vendors" ON public.vendors;
CREATE POLICY "owners can manage vendors" ON public.vendors
  FOR ALL TO authenticated USING (private.is_owner()) WITH CHECK (private.is_owner());

-- stock_items
DROP POLICY IF EXISTS "active users can read stock items" ON public.stock_items;
CREATE POLICY "active users can read stock items" ON public.stock_items
  FOR SELECT TO authenticated USING (private.is_active_app_user());

DROP POLICY IF EXISTS "owners can manage stock items" ON public.stock_items;
CREATE POLICY "owners can manage stock items" ON public.stock_items
  FOR ALL TO authenticated USING (private.is_owner()) WITH CHECK (private.is_owner());

-- purchase_bills
DROP POLICY IF EXISTS "owners can manage purchase bills" ON public.purchase_bills;
CREATE POLICY "owners can manage purchase bills" ON public.purchase_bills
  FOR ALL TO authenticated USING (private.is_owner()) WITH CHECK (private.is_owner());

DROP POLICY IF EXISTS "staff can read own purchase bills" ON public.purchase_bills;
CREATE POLICY "staff can read own purchase bills" ON public.purchase_bills
  FOR SELECT TO authenticated
  USING (created_by = (SELECT auth.uid()) AND private.is_active_app_user());

DROP POLICY IF EXISTS "staff can create purchase bills" ON public.purchase_bills;
CREATE POLICY "staff can create purchase bills" ON public.purchase_bills
  FOR INSERT TO authenticated
  WITH CHECK (created_by = (SELECT auth.uid()) AND private.is_active_app_user()
              AND status IN ('draft','pending_review')
              AND approved_by IS NULL AND approved_at IS NULL);

DROP POLICY IF EXISTS "staff can update own unapproved purchase bills" ON public.purchase_bills;
CREATE POLICY "staff can update own unapproved purchase bills" ON public.purchase_bills
  FOR UPDATE TO authenticated
  USING (created_by = (SELECT auth.uid()) AND private.is_active_app_user()
         AND status IN ('draft','pending_review'))
  WITH CHECK (created_by = (SELECT auth.uid()) AND private.is_active_app_user()
              AND status IN ('draft','pending_review')
              AND approved_by IS NULL AND approved_at IS NULL);

-- purchase_bill_items
DROP POLICY IF EXISTS "users can read accessible bill items" ON public.purchase_bill_items;
CREATE POLICY "users can read accessible bill items" ON public.purchase_bill_items
  FOR SELECT TO authenticated USING (private.can_access_bill(purchase_bill_id));

DROP POLICY IF EXISTS "users can manage editable bill items" ON public.purchase_bill_items;
CREATE POLICY "users can manage editable bill items" ON public.purchase_bill_items
  FOR ALL TO authenticated
  USING (private.can_manage_bill_lines(purchase_bill_id))
  WITH CHECK (private.can_manage_bill_lines(purchase_bill_id));

-- stock_movements
DROP POLICY IF EXISTS "active users can read stock movements" ON public.stock_movements;
CREATE POLICY "active users can read stock movements" ON public.stock_movements
  FOR SELECT TO authenticated USING (private.is_active_app_user());

DROP POLICY IF EXISTS "owners can create stock movements" ON public.stock_movements;
CREATE POLICY "owners can create stock movements" ON public.stock_movements
  FOR INSERT TO authenticated WITH CHECK (private.is_owner());

DROP POLICY IF EXISTS "owners can update stock movements" ON public.stock_movements;
CREATE POLICY "owners can update stock movements" ON public.stock_movements
  FOR UPDATE TO authenticated USING (private.is_owner()) WITH CHECK (private.is_owner());

DROP POLICY IF EXISTS "owners can delete stock movements" ON public.stock_movements;
CREATE POLICY "owners can delete stock movements" ON public.stock_movements
  FOR DELETE TO authenticated USING (private.is_owner());

-- bill_alerts
DROP POLICY IF EXISTS "users can read bill alerts" ON public.bill_alerts;
CREATE POLICY "users can read bill alerts" ON public.bill_alerts
  FOR SELECT TO authenticated
  USING (private.can_access_bill(purchase_bill_id));

DROP POLICY IF EXISTS "users can update bill alerts" ON public.bill_alerts;
DROP POLICY IF EXISTS "owners can update bill alerts" ON public.bill_alerts;
CREATE POLICY "owners can update bill alerts" ON public.bill_alerts
  FOR UPDATE TO authenticated
  USING (private.is_owner())
  WITH CHECK (private.is_owner());

-- system_config
-- Secrets (e.g. hf_api_key) live here. No SELECT policy via PostgREST — RLS
-- denies all reads by anon/authenticated. The edge function reads its secret
-- from Deno.env, and service_role bypasses RLS for any future admin tooling.
DROP POLICY IF EXISTS "Allow read access to authenticated users" ON public.system_config;


-- =====================================================================
-- 10. SEED DATA (essential master rows — NOT demo data)
-- =====================================================================

INSERT INTO public.roles (code, label) VALUES
  ('owner', 'Owner'),
  ('staff', 'Staff')
ON CONFLICT (code) DO NOTHING;


-- =====================================================================
-- DONE.
-- Next steps for the new client:
--   1. Create the first auth user via Authentication > Users in dashboard.
--   2. Run:
--        INSERT INTO public.users (id, role_id, full_name, is_active)
--        VALUES (
--          '<paste-the-new-auth-user-uuid-here>',
--          (SELECT id FROM public.roles WHERE code = 'owner'),
--          'Client Owner Name',
--          true
--        );
--   3. They can now log in and use the app.
-- =====================================================================
