create extension if not exists pgcrypto;
create schema if not exists private;

-- Phase 1 replaces the earlier menu/outlet prototype with a single-outlet stock tracker.
-- Run this against the prototype database only after you are ready to discard old demo data.
drop view if exists public.stock_item_balances cascade;
drop view if exists public.user_access_view cascade;
drop view if exists public.public_daily_menu_view cascade;

drop table if exists public.stock_movements cascade;
drop table if exists public.purchase_bill_items cascade;
drop table if exists public.purchase_bills cascade;
drop table if exists public.vendors cascade;
drop table if exists public.stock_items cascade;
drop table if exists public.daily_menu_items cascade;
drop table if exists public.daily_menus cascade;
drop table if exists public.ingredients cascade;
drop table if exists public.dishes cascade;
drop table if exists public.outlets cascade;
drop table if exists public.users cascade;
drop table if exists public.roles cascade;

drop function if exists private.can_manage_bill_lines(uuid);
drop function if exists private.can_access_bill(uuid);
drop function if exists private.is_active_app_user();
drop function if exists private.is_owner();
drop function if exists private.current_user_role();
drop function if exists private.can_access_outlet(uuid);
drop function if exists private.current_outlet_id();
drop function if exists private.is_hq();
drop function if exists public.enforce_user_outlet_rule();
drop function if exists public.set_daily_menu_audit_fields();

create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  code text not null unique,
  label text not null unique,
  created_at timestamptz not null default timezone('utc', now()),
  constraint roles_code_check check (code in ('owner', 'staff'))
);

create table if not exists public.users (
  id uuid primary key references auth.users (id) on delete cascade,
  role_id bigint not null references public.roles (id) on delete restrict,
  full_name text,
  phone text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.stock_items (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  category text not null,
  default_unit text not null,
  low_stock_threshold numeric(12, 3) not null default 0,
  is_active boolean not null default true,
  notes text,
  created_by uuid references auth.users (id) on delete set null default auth.uid(),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint stock_items_low_stock_threshold_check check (low_stock_threshold >= 0)
);

create table if not exists public.vendors (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  contact_name text,
  phone text,
  category_supplied text,
  notes text,
  is_active boolean not null default true,
  created_by uuid references auth.users (id) on delete set null default auth.uid(),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.purchase_bills (
  id uuid primary key default gen_random_uuid(),
  vendor_id uuid references public.vendors (id) on delete restrict,
  bill_date date not null default current_date,
  bill_number text,
  source text not null default 'manual',
  original_text text,
  file_url text,
  subtotal numeric(12, 2) not null default 0,
  extra_charges numeric(12, 2) not null default 0,
  total numeric(12, 2) not null default 0,
  status text not null default 'draft',
  created_by uuid references auth.users (id) on delete set null default auth.uid(),
  approved_by uuid references auth.users (id) on delete set null,
  approved_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint purchase_bills_status_check check (status in ('draft', 'pending_review', 'approved', 'rejected')),
  constraint purchase_bills_source_check check (source in ('manual', 'whatsapp_paste', 'upload')),
  constraint purchase_bills_money_check check (subtotal >= 0 and extra_charges >= 0 and total >= 0),
  constraint purchase_bills_approval_check check (
    (status = 'approved' and approved_by is not null and approved_at is not null)
    or (status <> 'approved')
  )
);

create table if not exists public.purchase_bill_items (
  id uuid primary key default gen_random_uuid(),
  purchase_bill_id uuid not null references public.purchase_bills (id) on delete cascade,
  stock_item_id uuid references public.stock_items (id) on delete restrict,
  raw_item_name text not null,
  quantity numeric(12, 3) not null,
  unit text not null,
  unit_price numeric(12, 2) not null,
  line_total numeric(12, 2) not null,
  confidence_score numeric(5, 2),
  match_status text not null default 'manual_match',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint purchase_bill_items_quantity_check check (quantity > 0),
  constraint purchase_bill_items_money_check check (unit_price >= 0 and line_total >= 0),
  constraint purchase_bill_items_confidence_score_check check (confidence_score is null or confidence_score between 0 and 100),
  constraint purchase_bill_items_match_status_check check (match_status in ('matched', 'manual_match', 'unknown', 'needs_review'))
);

create table if not exists public.stock_movements (
  id uuid primary key default gen_random_uuid(),
  stock_item_id uuid not null references public.stock_items (id) on delete restrict,
  movement_type text not null,
  quantity numeric(12, 3) not null,
  unit text not null,
  source_bill_item_id uuid references public.purchase_bill_items (id) on delete restrict,
  notes text,
  created_by uuid references auth.users (id) on delete set null default auth.uid(),
  created_at timestamptz not null default timezone('utc', now()),
  constraint stock_movements_quantity_check check (quantity > 0),
  constraint stock_movements_type_check check (
    movement_type in ('opening_stock', 'purchase_added', 'usage', 'wastage', 'return_to_vendor', 'correction')
  ),
  constraint stock_movements_purchase_source_check check (
    movement_type <> 'purchase_added' or source_bill_item_id is not null
  )
);

create index if not exists users_role_id_idx on public.users (role_id);
create index if not exists stock_items_active_category_idx on public.stock_items (is_active, category);
create index if not exists vendors_active_name_idx on public.vendors (is_active, name);
create index if not exists purchase_bills_vendor_date_idx on public.purchase_bills (vendor_id, bill_date desc);
create index if not exists purchase_bills_status_date_idx on public.purchase_bills (status, bill_date desc);
create unique index if not exists purchase_bills_vendor_bill_number_unique_idx
  on public.purchase_bills (vendor_id, bill_number)
  where bill_number is not null;
create index if not exists purchase_bill_items_bill_id_idx on public.purchase_bill_items (purchase_bill_id);
create index if not exists purchase_bill_items_stock_item_id_idx on public.purchase_bill_items (stock_item_id);
create index if not exists stock_movements_item_created_idx on public.stock_movements (stock_item_id, created_at desc);
create index if not exists stock_movements_source_bill_item_id_idx on public.stock_movements (source_bill_item_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at
before update on public.users
for each row
execute function public.set_updated_at();

drop trigger if exists stock_items_set_updated_at on public.stock_items;
create trigger stock_items_set_updated_at
before update on public.stock_items
for each row
execute function public.set_updated_at();

drop trigger if exists vendors_set_updated_at on public.vendors;
create trigger vendors_set_updated_at
before update on public.vendors
for each row
execute function public.set_updated_at();

drop trigger if exists purchase_bills_set_updated_at on public.purchase_bills;
create trigger purchase_bills_set_updated_at
before update on public.purchase_bills
for each row
execute function public.set_updated_at();

drop trigger if exists purchase_bill_items_set_updated_at on public.purchase_bill_items;
create trigger purchase_bill_items_set_updated_at
before update on public.purchase_bill_items
for each row
execute function public.set_updated_at();

create or replace function private.current_user_role()
returns text
language sql
security definer
set search_path = public, private
as $$
  select r.code
  from public.users u
  join public.roles r on r.id = u.role_id
  where u.id = (select auth.uid())
    and u.is_active
  limit 1
$$;

create or replace function private.is_owner()
returns boolean
language sql
security definer
set search_path = public, private
as $$
  select coalesce(private.current_user_role() = 'owner', false)
$$;

create or replace function private.is_active_app_user()
returns boolean
language sql
security definer
set search_path = public, private
as $$
  select private.current_user_role() in ('owner', 'staff')
$$;

create or replace function private.can_access_bill(target_bill_id uuid)
returns boolean
language sql
security definer
set search_path = public, private
as $$
  select exists (
    select 1
    from public.purchase_bills b
    where b.id = target_bill_id
      and (
        private.is_owner()
        or b.created_by = (select auth.uid())
      )
  )
$$;

create or replace function private.can_manage_bill_lines(target_bill_id uuid)
returns boolean
language sql
security definer
set search_path = public, private
as $$
  select exists (
    select 1
    from public.purchase_bills b
    where b.id = target_bill_id
      and (
        private.is_owner()
        or (
          b.created_by = (select auth.uid())
          and b.status in ('draft', 'pending_review')
        )
      )
  )
$$;

revoke all on schema private from public;
grant usage on schema private to authenticated;
grant usage on schema private to service_role;
grant execute on function private.current_user_role() to authenticated, service_role;
grant execute on function private.is_owner() to authenticated, service_role;
grant execute on function private.is_active_app_user() to authenticated, service_role;
grant execute on function private.can_access_bill(uuid) to authenticated, service_role;
grant execute on function private.can_manage_bill_lines(uuid) to authenticated, service_role;

insert into public.roles (code, label)
values
  ('owner', 'Owner'),
  ('staff', 'Staff')
on conflict (code) do update
set label = excluded.label;

alter table public.roles enable row level security;
alter table public.users enable row level security;
alter table public.stock_items enable row level security;
alter table public.vendors enable row level security;
alter table public.purchase_bills enable row level security;
alter table public.purchase_bill_items enable row level security;
alter table public.stock_movements enable row level security;

grant select on public.roles to authenticated;
grant select, insert, update on public.users to authenticated;
grant select, insert, update, delete on public.stock_items to authenticated;
grant select, insert, update, delete on public.vendors to authenticated;
grant select, insert, update, delete on public.purchase_bills to authenticated;
grant select, insert, update, delete on public.purchase_bill_items to authenticated;
grant select, insert on public.stock_movements to authenticated;

grant all on public.roles to service_role;
grant all on public.users to service_role;
grant all on public.stock_items to service_role;
grant all on public.vendors to service_role;
grant all on public.purchase_bills to service_role;
grant all on public.purchase_bill_items to service_role;
grant all on public.stock_movements to service_role;

drop policy if exists "authenticated users can read roles" on public.roles;
create policy "authenticated users can read roles"
on public.roles
for select
to authenticated
using ((select auth.uid()) is not null);

drop policy if exists "users can read own profile" on public.users;
create policy "users can read own profile"
on public.users
for select
to authenticated
using (id = (select auth.uid()));

drop policy if exists "owners can read all users" on public.users;
create policy "owners can read all users"
on public.users
for select
to authenticated
using (private.is_owner());

drop policy if exists "owners can manage users" on public.users;
create policy "owners can manage users"
on public.users
for all
to authenticated
using (private.is_owner())
with check (private.is_owner());

drop policy if exists "active users can read stock items" on public.stock_items;
create policy "active users can read stock items"
on public.stock_items
for select
to authenticated
using (private.is_active_app_user());

drop policy if exists "owners can manage stock items" on public.stock_items;
create policy "owners can manage stock items"
on public.stock_items
for all
to authenticated
using (private.is_owner())
with check (private.is_owner());

drop policy if exists "active users can read vendors" on public.vendors;
create policy "active users can read vendors"
on public.vendors
for select
to authenticated
using (private.is_active_app_user());

drop policy if exists "owners can manage vendors" on public.vendors;
create policy "owners can manage vendors"
on public.vendors
for all
to authenticated
using (private.is_owner())
with check (private.is_owner());

drop policy if exists "owners can manage purchase bills" on public.purchase_bills;
create policy "owners can manage purchase bills"
on public.purchase_bills
for all
to authenticated
using (private.is_owner())
with check (private.is_owner());

drop policy if exists "staff can read own purchase bills" on public.purchase_bills;
create policy "staff can read own purchase bills"
on public.purchase_bills
for select
to authenticated
using (created_by = (select auth.uid()) and private.is_active_app_user());

drop policy if exists "staff can create purchase bills" on public.purchase_bills;
create policy "staff can create purchase bills"
on public.purchase_bills
for insert
to authenticated
with check (
  created_by = (select auth.uid())
  and private.is_active_app_user()
  and status in ('draft', 'pending_review')
  and approved_by is null
  and approved_at is null
);

drop policy if exists "staff can update own unapproved purchase bills" on public.purchase_bills;
create policy "staff can update own unapproved purchase bills"
on public.purchase_bills
for update
to authenticated
using (
  created_by = (select auth.uid())
  and private.is_active_app_user()
  and status in ('draft', 'pending_review')
)
with check (
  created_by = (select auth.uid())
  and private.is_active_app_user()
  and status in ('draft', 'pending_review')
  and approved_by is null
  and approved_at is null
);

drop policy if exists "users can read accessible bill items" on public.purchase_bill_items;
create policy "users can read accessible bill items"
on public.purchase_bill_items
for select
to authenticated
using (private.can_access_bill(purchase_bill_id));

drop policy if exists "users can manage editable bill items" on public.purchase_bill_items;
create policy "users can manage editable bill items"
on public.purchase_bill_items
for all
to authenticated
using (private.can_manage_bill_lines(purchase_bill_id))
with check (private.can_manage_bill_lines(purchase_bill_id));

drop policy if exists "active users can read stock movements" on public.stock_movements;
create policy "active users can read stock movements"
on public.stock_movements
for select
to authenticated
using (private.is_active_app_user());

drop policy if exists "owners can create stock movements" on public.stock_movements;
create policy "owners can create stock movements"
on public.stock_movements
for insert
to authenticated
with check (private.is_owner());

drop policy if exists "owners can update stock movements" on public.stock_movements;
create policy "owners can update stock movements"
on public.stock_movements
for update
to authenticated
using (private.is_owner())
with check (private.is_owner());

drop policy if exists "owners can delete stock movements" on public.stock_movements;
create policy "owners can delete stock movements"
on public.stock_movements
for delete
to authenticated
using (private.is_owner());

create or replace view public.user_access_view
with (security_invoker = true)
as
select
  u.id,
  u.full_name,
  u.phone,
  u.is_active,
  r.code as role_code,
  r.label as role_label
from public.users u
join public.roles r on r.id = u.role_id;

create or replace view public.stock_item_balances
with (security_invoker = true)
as
select
  si.id as stock_item_id,
  si.name,
  si.category,
  si.default_unit,
  si.low_stock_threshold,
  si.is_active,
  coalesce(
    sum(
      case sm.movement_type
        when 'opening_stock' then sm.quantity
        when 'purchase_added' then sm.quantity
        when 'usage' then -sm.quantity
        when 'wastage' then -sm.quantity
        when 'return_to_vendor' then -sm.quantity
        when 'correction' then sm.quantity
        else 0
      end
    ),
    0
  ) as current_quantity,
  coalesce(
    sum(
      case sm.movement_type
        when 'opening_stock' then sm.quantity
        when 'purchase_added' then sm.quantity
        when 'usage' then -sm.quantity
        when 'wastage' then -sm.quantity
        when 'return_to_vendor' then -sm.quantity
        when 'correction' then sm.quantity
        else 0
      end
    ),
    0
  ) <= si.low_stock_threshold as is_low_stock
from public.stock_items si
left join public.stock_movements sm on sm.stock_item_id = si.id
group by si.id;

grant select on public.user_access_view to authenticated;
grant select on public.stock_item_balances to authenticated;
grant select on public.user_access_view to service_role;
grant select on public.stock_item_balances to service_role;

comment on table public.roles is 'Owner/staff role master for the stock tracker.';
comment on table public.users is 'App user profile linked 1:1 with auth.users.';
comment on table public.stock_items is 'Single-outlet stock item master.';
comment on table public.vendors is 'Approved supplier master.';
comment on table public.purchase_bills is 'Supplier bill header before and after owner approval.';
comment on table public.purchase_bill_items is 'Supplier bill line items mapped to stock items when possible.';
comment on table public.stock_movements is 'Traceable stock ledger entries. Purchase stock increases must reference a bill line.';
comment on view public.stock_item_balances is 'Current stock quantity calculated from stock movements.';

-- Example profile inserts after creating auth users in Supabase Auth:
-- insert into public.users (id, role_id, full_name)
-- values (
--   'AUTH-USER-UUID-HERE',
--   (select id from public.roles where code = 'owner'),
--   'Restaurant Owner'
-- );
--
-- insert into public.users (id, role_id, full_name)
-- values (
--   'AUTH-USER-UUID-HERE',
--   (select id from public.roles where code = 'staff'),
--   'Kitchen Manager'
-- );
