create extension if not exists pgcrypto;
create schema if not exists private;

create table if not exists public.outlets (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null unique,
  city text not null,
  state_region text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  code text not null unique,
  label text not null unique,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.users (
  id uuid primary key references auth.users (id) on delete cascade,
  role_id bigint not null references public.roles (id),
  outlet_id uuid references public.outlets (id),
  full_name text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists users_role_id_idx on public.users (role_id);
create index if not exists users_outlet_id_idx on public.users (outlet_id);

create or replace function private.is_hq()
returns boolean
language plpgsql
security definer
set search_path = public, private
as $$
begin
  return exists (
    select 1
    from public.users u
    join public.roles r on r.id = u.role_id
    where u.id = (select auth.uid())
      and u.is_active
      and r.code = 'hq'
  );
end;
$$;

create or replace function private.current_outlet_id()
returns uuid
language sql
security definer
set search_path = public, private
as $$
  select u.outlet_id
  from public.users u
  where u.id = (select auth.uid())
    and u.is_active
  limit 1
$$;

revoke all on schema private from public;
grant usage on schema private to authenticated;
grant usage on schema private to service_role;
grant execute on function private.is_hq() to authenticated;
grant execute on function private.current_outlet_id() to authenticated;
grant execute on function private.is_hq() to service_role;
grant execute on function private.current_outlet_id() to service_role;

insert into public.roles (code, label)
values
  ('hq', 'HQ'),
  ('manager', 'Outlet Manager')
on conflict (code) do update
set label = excluded.label;

insert into public.outlets (code, name, city, state_region)
values
  ('DEL-NCR', 'Delhi NCR', 'Delhi NCR', 'Delhi NCR'),
  ('GAU', 'Guwahati', 'Guwahati', 'Assam'),
  ('PAT', 'Patna', 'Patna', 'Bihar')
on conflict (code) do update
set
  name = excluded.name,
  city = excluded.city,
  state_region = excluded.state_region;

create or replace function public.enforce_user_outlet_rule()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  role_code text;
begin
  select r.code into role_code
  from public.roles r
  where r.id = new.role_id;

  if role_code is null then
    raise exception 'Role % does not exist.', new.role_id;
  end if;

  if role_code = 'manager' and new.outlet_id is null then
    raise exception 'Managers must be assigned to an outlet.';
  end if;

  if role_code = 'hq' and new.outlet_id is not null then
    raise exception 'HQ users must not be pinned to a single outlet.';
  end if;

  return new;
end;
$$;

drop trigger if exists users_enforce_outlet_rule on public.users;
create trigger users_enforce_outlet_rule
before insert or update on public.users
for each row
execute function public.enforce_user_outlet_rule();

alter table public.outlets enable row level security;
alter table public.roles enable row level security;
alter table public.users enable row level security;

drop policy if exists "authenticated users can read roles" on public.roles;
create policy "authenticated users can read roles"
on public.roles
for select
to authenticated
using ((select auth.uid()) is not null);

drop policy if exists "hq can read all outlets" on public.outlets;
create policy "hq can read all outlets"
on public.outlets
for select
to authenticated
using (
  private.is_hq()
);

drop policy if exists "managers can read their outlet" on public.outlets;
create policy "managers can read their outlet"
on public.outlets
for select
to authenticated
using (
  id = private.current_outlet_id()
);

drop policy if exists "users can read their own profile" on public.users;
create policy "users can read their own profile"
on public.users
for select
to authenticated
using (
  (select auth.uid()) is not null
  and id = (select auth.uid())
);

drop policy if exists "hq can read all users" on public.users;
create policy "hq can read all users"
on public.users
for select
to authenticated
using (
  private.is_hq()
);

drop policy if exists "hq can manage users" on public.users;
create policy "hq can manage users"
on public.users
for all
to authenticated
using (
  private.is_hq()
)
with check (
  private.is_hq()
);

comment on table public.users is 'App user profile linked 1:1 with auth.users.';

create or replace view public.user_access_view
with (security_invoker = true)
as
select
  u.id,
  u.full_name,
  u.is_active,
  r.code as role_code,
  r.label as role_label,
  o.id as outlet_id,
  o.code as outlet_code,
  o.name as outlet_name,
  o.city,
  o.state_region
from public.users u
join public.roles r on r.id = u.role_id
left join public.outlets o on o.id = u.outlet_id;

grant select on public.outlets to authenticated;
grant select on public.roles to authenticated;
grant select, insert, update on public.users to authenticated;
grant select on public.user_access_view to authenticated;
grant all on public.outlets to service_role;
grant all on public.roles to service_role;
grant all on public.users to service_role;
grant select on public.user_access_view to service_role;

-- Example inserts after you create auth users in Supabase Auth:
-- insert into public.users (id, role_id, outlet_id, full_name)
-- values (
--   'AUTH-USER-UUID-HERE',
--   (select id from public.roles where code = 'manager'),
--   (select id from public.outlets where code = 'DEL-NCR'),
--   'Delhi Manager'
-- );
--
-- insert into public.users (id, role_id, full_name)
-- values (
--   'AUTH-USER-UUID-HERE',
--   (select id from public.roles where code = 'hq'),
--   'HQ Owner'
-- );
